### ISSUE TITLE
[CoreTypes] Tracking

### ISSUE THREAD

**Issue by rvagg** [protocol/w3dt-sudo#17]
Some low-overhead tracking for ongoing work for the [TypeScript Definitions for core libraries](https://github.com/protocol/web3-dev-team/pull/79) project.

Items can be ticked off as closed, new items can be added on-going (edit this message).

### js-ipfs

0.55 project board: https://github.com/orgs/ipfs/projects/6

Tracking: https://github.com/ipfs/js-ipfs/issues/2945

* [ ] https://github.com/ipfs/js-ipfs/pull/3607
* [x] https://github.com/ipfs/js-ipfsd-ctl/pull/628
* [x] https://github.com/ipfs-shipyard/is-ipfs/pull/41
* [x] https://github.com/ipfs/js-ipfs-bitswap/pull/321
* [x] https://github.com/ipfs/js-ipfs-unixfs/pull/144
* [x] https://github.com/ipfs/js-datastore-s3/pull/34
* [x] https://github.com/ipfs/js-datastore-fs/pull/82
* [x] https://github.com/ipfs/js-datastore-level/pull/70
* [x] https://github.com/ipfs/js-datastore-core/pull/59
* [x] https://github.com/ipfs/interface-datastore/pull/87
* [x] https://github.com/ipfs/js-datastore-level/pull/69
* [x] https://github.com/ipfs/js-ipfs-repo/pull/302
* [x] https://github.com/ipfs/js-ipfs-utils/pull/120
* [x] https://github.com/ipfs/js-datastore-fs/pull/81
* [x] https://github.com/ipfs/interface-datastore/pull/85
* [x] https://github.com/ipfs/js-ipfs-bitswap/pull/319
* [x] https://github.com/ipfs/js-datastore-s3/pull/33
* [x] https://github.com/ipfs/js-datastore-s3/pull/32
* [x] https://github.com/ipfs/js-ipfs-http-response/pull/86
* [x] https://github.com/ipfs/interop/pull/265
* [x] https://github.com/ipfs/js-ipfsd-ctl/pull/623

### js-libp2p

* [ ] https://github.com/libp2p/js-libp2p/pull/912
* [ ] https://github.com/NodeFactoryIo/js-libp2p-noise/pull/94
* [x] https://github.com/libp2p/js-libp2p/pull/904
* [x] https://github.com/libp2p/js-libp2p/pull/914
* [x] https://github.com/libp2p/js-libp2p/pull/915
* [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/112
* [x] https://github.com/libp2p/js-libp2p-bootstrap/pull/113
* [x] https://github.com/libp2p/js-libp2p-floodsub/pull/114
* [x] https://github.com/libp2p/js-libp2p-interfaces/pull/89
* [x] https://github.com/libp2p/js-libp2p-mdns/pull/98
* [x] https://github.com/libp2p/js-libp2p-tcp/pull/144
* [x] https://github.com/libp2p/js-libp2p-utils/pull/17
* [x] https://github.com/libp2p/js-libp2p-websockets/pull/124
* [x] https://github.com/libp2p/js-libp2p-crypto/pull/187
* [x] https://github.com/libp2p/js-peer-id/pull/145
* [x] https://github.com/multiformats/js-mafmt/pull/79
* [x] https://github.com/libp2p/js-libp2p-webrtc-star/pull/329
* [x] https://github.com/libp2p/js-libp2p-webrtc-direct/pull/116
* [ ] https://github.com/libp2p/js-libp2p-kad-dht/pull/217 (needs libp2p release)
* [ ] https://github.com/ChainSafe/js-libp2p-gossipsub/pull/153 (needs libp2p release)
* [x] https://github.com/libp2p/js-libp2p/pull/915
* [x] https://github.com/libp2p/js-libp2p-mplex/pull/119
* [x] https://github.com/libp2p/js-libp2p-floodsub/pull/115
* [x] https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/44
* [x] https://github.com/libp2p/js-libp2p-delegated-content-routing/pull/50
* [x] https://github.com/multiformats/js-multistream-select/pull/128
* [x] https://github.com/libp2p/js-libp2p-record/pull/26

### ipld

* [x] https://github.com/ipld/js-dag-cbor/pull/18
  - [x] https://github.com/ipld/js-dag-cbor/pull/16
* [x] https://github.com/ipld/js-dag-pb/pull/6
* [x] https://github.com/ipld/js-dag-json/pull/29
* [x] https://github.com/ipld/js-car/pull/7
* [x] https://github.com/multiformats/js-multiformats/pull/75
* [x] https://github.com/multiformats/js-uri-to-multiaddr/pull/16
* [x] https://github.com/multiformats/js-mafmt/pull/79
* [x] https://github.com/ipld/js-ipld-ethereum/pull/71
* [x] https://github.com/multiformats/js-cid-tool/pull/11

## downstream

* [ ] https://github.com/ceramicnetwork/js-ceramic/pull/1194

## web-encoding, buffer, bl

* [x] https://github.com/Gozala/web-encoding/pull/21
* [x] https://github.com/ipfs/js-ipfs-http-response/pull/86
* [x] https://github.com/mkg20001/it-buffer/pull/2
* [x] https://github.com/multiformats/js-multiaddr-to-uri/pull/66
* [x] https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52236

## external or supporting modules

* [x] https://github.com/alanshaw/it-length-prefixed/pull/13
* [x] https://github.com/alanshaw/it-length-prefixed/pull/15
* [x] https://github.com/alanshaw/stream-to-it/pull/13
* [x] https://github.com/alanshaw/it-concat/pull/7
* [x] https://github.com/alanshaw/it-tar/pull/4
* [x] https://github.com/hugomrdias/rabin-wasm/pull/166
* [x] https://github.com/mkg20001/it-pb-rpc/pull/10
* [x] https://github.com/achingbrain/uint8arrays/pull/18
* [x] https://github.com/Level/level/pull/194
* [x] https://github.com/jacobheun/it-handshake/pull/3
* [ ] https://github.com/dignifiedquire/borc/pull/53
* [x] https://github.com/alanshaw/it-reader/pull/6
* [x] https://github.com/alanshaw/it-block/pull/4
